# Generated by Django 5.0 on 2023-12-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('quartier', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=30)),
                ('cv', models.FileField(upload_to='')),
                ('lettre_motivation', models.FileField(upload_to='')),
                ('experience', models.CharField(max_length=255)),
                ('diplome', models.CharField(max_length=255)),
            ],
        ),
    ]
