# Generated by Django 4.2.8 on 2023-12-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaire',
            name='genre',
            field=models.CharField(default='Femme', max_length=255),
            preserve_default=False,
        ),
    ]
