# Generated by Django 4.2.8 on 2023-12-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0002_formulaire_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaire',
            name='attestion',
            field=models.FileField(default='1', upload_to=''),
            preserve_default=False,
        ),
    ]
