# Generated by Django 4.2.8 on 2023-12-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0003_formulaire_attestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaire',
            name='preselectionner',
            field=models.BooleanField(default=False),
        ),
    ]
