# Generated by Django 4.2.8 on 2023-12-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0004_formulaire_preselectionner'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaire',
            name='rejeter',
            field=models.BooleanField(default=False),
        ),
    ]
