# Generated by Django 4.2.8 on 2023-12-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0005_formulaire_rejeter'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaire',
            name='contacter',
            field=models.BooleanField(default=False),
        ),
    ]
